check packs

diff --git a/.github/workflows/check-packs.yml b/.github/workflows/check-packs.yml
--- a/.github/workflows/check-packs.yml
+++ b/.github/workflows/check-packs.yml
@@ -41,7 +41,12 @@ jobs:
           panther_analysis_tool check-packs 2> errors.txt || true
 
           # run again to get exit code
-          panther_analysis_tool check-packs || echo "errors=`cat errors.txt`" >> $GITHUB_OUTPUT
+          # panther_analysis_tool check-packs || echo "errors=`cat errors.txt`" >> $GITHUB_OUTPUT
+          {
+            echo "errors<<EOF"
+            panther_analysis_tool check-packs
+            echo "EOF"
+          }
 
       - name: Comment PR
         uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6
